# Generated by Django 2.2 on 2020-05-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value1', models.IntegerField(default=0)),
                ('value2', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Alert Setting',
                'verbose_name_plural': 'Alert Settings',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='AlertStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('level', models.IntegerField()),
                ('status', models.BooleanField()),
                ('alert_read', models.BooleanField()),
                ('alert_delete', models.BooleanField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Alert Status',
                'verbose_name_plural': 'Alert Status',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='AlertType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_name', models.CharField(max_length=100)),
                ('alert_formula', models.CharField(max_length=100)),
                ('report_date', models.CharField(blank=True, max_length=100, null=True)),
                ('alert_day', models.CharField(blank=True, max_length=100, null=True)),
                ('alert_hour', models.CharField(blank=True, max_length=100, null=True)),
                ('sms', models.BooleanField()),
                ('email', models.BooleanField()),
                ('bot', models.BooleanField()),
                ('status', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Alert Type',
                'verbose_name_plural': 'Alert Types',
                'ordering': ['pk'],
            },
        ),
    ]
