# Generated by Django 2.2 on 2020-05-09 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lotus_dashboard', '0001_initial'),
        ('lotus_alert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertstatus',
            name='crm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotus_dashboard.CrmAccount'),
        ),
        migrations.AddField(
            model_name='alertstatus',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotus_alert.AlertType'),
        ),
        migrations.AddField(
            model_name='alertsetting',
            name='crm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotus_dashboard.CrmAccount'),
        ),
        migrations.AddField(
            model_name='alertsetting',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotus_alert.AlertType'),
        ),
    ]
