# Generated by Django 2.2 on 2020-05-09 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('sites', '0002_alter_domain_unique'),
        ('lotus_dashboard', '0001_initial'),
        ('lotus_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotususer',
            name='crm_permissions',
            field=models.ManyToManyField(blank=True, to='lotus_dashboard.CrmAccount'),
        ),
        migrations.AddField(
            model_name='lotususer',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
        migrations.AddField(
            model_name='lotususer',
            name='site_joined',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
        migrations.AddField(
            model_name='lotususer',
            name='sites_logged',
            field=models.ManyToManyField(blank=True, related_name='users_logged', to='sites.Site'),
        ),
        migrations.AddField(
            model_name='lotususer',
            name='sites_subscribed',
            field=models.ManyToManyField(blank=True, related_name='subscribed_users', to='sites.Site'),
        ),
        migrations.AddField(
            model_name='lotususer',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, to='auth.Permission'),
        ),
    ]
