# Generated by Django 2.2 on 2020-05-09 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('afid', models.CharField(max_length=128)),
                ('code', models.CharField(blank=True, max_length=16, null=True)),
                ('bot', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'verbose_name': 'Affiliate',
                'verbose_name_plural': 'Affiliates',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='BillingAffiliate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('afid', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Billing Affiliate',
                'verbose_name_plural': 'Affiliates of Billing',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Blocked IP',
                'verbose_name_plural': 'Blocked IPs',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='CrmAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_name', models.CharField(max_length=100, unique=True)),
                ('crm_url', models.URLField(max_length=255)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('api_username', models.CharField(max_length=100)),
                ('api_password', models.CharField(max_length=100)),
                ('sales_goal', models.IntegerField(default=0)),
                ('paused', models.BooleanField(default=False)),
                ('password_updated', models.DateField(blank=True, null=True)),
                ('rebill_length', models.IntegerField(blank=True, null=True)),
                ('test_cc', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'verbose_name': 'CRM Account',
                'verbose_name_plural': 'CRM Accounts',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('type', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Label',
                'verbose_name_plural': 'Labels',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='LabelCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.IntegerField()),
                ('campaign_name', models.CharField(max_length=128)),
                ('campaign_type', models.IntegerField(blank=True, choices=[(1, 'Step1'), (2, 'Step2'), (3, 'Prepaids'), (4, 'Tablet'), (5, 'MC Step1'), (6, 'MC Step2')], null=True)),
                ('campaign_format', models.IntegerField(blank=True, choices=[(1, 'Step1'), (2, 'Step2'), (3, 'Desktop'), (4, 'Mobile')], null=True)),
                ('pid', models.CharField(blank=True, max_length=255, null=True, verbose_name='Product IDs')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('crm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotus_dashboard.CrmAccount')),
                ('label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lotus_dashboard.Label')),
            ],
            options={
                'verbose_name': 'Label Campaign',
                'verbose_name_plural': 'Label Campaigns',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('type', models.IntegerField(choices=[(1, 'Single Step'), (2, '2 Step')], default=1)),
                ('s1_payout', models.IntegerField()),
                ('s2_payout', models.IntegerField(blank=True, null=True)),
                ('crm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotus_dashboard.CrmAccount')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='OfferLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Offer Label',
                'verbose_name_plural': 'Offer Labels',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='RebillResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('result', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('crm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotus_dashboard.CrmAccount')),
            ],
            options={
                'verbose_name': 'Rebill Result',
                'verbose_name_plural': 'Rebill Results',
            },
        ),
        migrations.CreateModel(
            name='Rebill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotus_dashboard.CrmAccount')),
                ('rebills', models.ManyToManyField(related_name='rebill', to='lotus_dashboard.LabelCampaign')),
            ],
            options={
                'verbose_name': 'Rebill List',
                'verbose_name_plural': 'Rebill List',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='OfferBilling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mc_desktop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_desktop_mc', to='lotus_dashboard.LabelCampaign')),
                ('mc_mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_mobile_mc', to='lotus_dashboard.LabelCampaign')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotus_dashboard.Offer')),
                ('trial_desktop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_desktop_trial', to='lotus_dashboard.LabelCampaign')),
                ('trial_mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_mobile_trial', to='lotus_dashboard.LabelCampaign')),
            ],
            options={
                'verbose_name': 'Billing Offer',
                'verbose_name_plural': 'Offers of Billing',
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotus_dashboard.OfferLabel'),
        ),
        migrations.AddField(
            model_name='offer',
            name='step1',
            field=models.ManyToManyField(related_name='offer_step1', to='lotus_dashboard.LabelCampaign'),
        ),
        migrations.AddField(
            model_name='offer',
            name='step1_prepaids',
            field=models.ManyToManyField(related_name='offer_step1_prepaids', to='lotus_dashboard.LabelCampaign'),
        ),
        migrations.AddField(
            model_name='offer',
            name='step1_tablet',
            field=models.ManyToManyField(blank=True, related_name='offer_step1_tablet', to='lotus_dashboard.LabelCampaign'),
        ),
        migrations.AddField(
            model_name='offer',
            name='step2',
            field=models.ManyToManyField(related_name='offer_step2', to='lotus_dashboard.LabelCampaign'),
        ),
        migrations.AddField(
            model_name='offer',
            name='step2_prepaids',
            field=models.ManyToManyField(related_name='offer_step2_prepaids', to='lotus_dashboard.LabelCampaign'),
        ),
        migrations.AddField(
            model_name='offer',
            name='step2_tablet',
            field=models.ManyToManyField(blank=True, related_name='offer_step2_tablet', to='lotus_dashboard.LabelCampaign'),
        ),
        migrations.CreateModel(
            name='LabelGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.IntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('crm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotus_dashboard.CrmAccount')),
                ('label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lotus_dashboard.Label')),
            ],
            options={
                'verbose_name': 'Label Goal',
                'verbose_name_plural': 'Label Goals',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='InitialResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('result', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('crm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotus_dashboard.CrmAccount')),
            ],
            options={
                'verbose_name': 'Initial Result',
                'verbose_name_plural': 'Initial Results',
            },
        ),
        migrations.CreateModel(
            name='DashboardColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columns', models.CharField(max_length=100)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard Column',
                'verbose_name_plural': 'Dashboard Columns',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='CrmToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('crm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotus_dashboard.CrmAccount')),
            ],
            options={
                'verbose_name': 'CRM Token',
                'verbose_name_plural': 'CRM Tokens',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='CrmResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('goal', models.IntegerField()),
                ('step1', models.IntegerField()),
                ('step2', models.IntegerField()),
                ('mc_step1', models.IntegerField()),
                ('mc_step2', models.IntegerField()),
                ('step1_nonpp', models.IntegerField()),
                ('step2_nonpp', models.IntegerField()),
                ('prepaids', models.IntegerField()),
                ('prepaids_step1', models.IntegerField()),
                ('prepaids_step2', models.IntegerField()),
                ('tablet_step1', models.IntegerField()),
                ('tablet_step2', models.IntegerField()),
                ('order_count', models.IntegerField()),
                ('order_page', models.FloatField()),
                ('declined', models.IntegerField()),
                ('gross_order', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('crm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotus_dashboard.CrmAccount')),
                ('label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lotus_dashboard.Label')),
            ],
            options={
                'verbose_name': 'CRM Result',
                'verbose_name_plural': 'CRM Results',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='CapUpdateResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('result', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('crm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotus_dashboard.CrmAccount')),
            ],
            options={
                'verbose_name': 'Cap Update Result',
                'verbose_name_plural': 'Cap Update Results',
            },
        ),
        migrations.CreateModel(
            name='BillingResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('trial_result', models.TextField()),
                ('mc_result', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotus_dashboard.OfferBilling')),
            ],
            options={
                'verbose_name': 'Billing Result',
                'verbose_name_plural': 'Billing Results',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='AffiliateOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.IntegerField()),
                ('s1_payout', models.IntegerField(blank=True, null=True)),
                ('s2_payout', models.IntegerField(blank=True, null=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotus_dashboard.Affiliate')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotus_dashboard.Offer')),
            ],
            options={
                'verbose_name': 'Affiliate Offer',
                'verbose_name_plural': 'Affiliate Offers',
                'ordering': ['affiliate', 'pk'],
            },
        ),
    ]
