# Generated by Django 2.2 on 2020-05-09 16:51

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, default=' ', max_length=180)),
                ('city', models.CharField(blank=True, default=' ', max_length=50)),
                ('state', localflavor.us.models.USStateField(blank=True, default=' ', max_length=2)),
                ('zip_code', models.CharField(blank=True, default=' ', max_length=10)),
                ('latitude', models.FloatField(blank=True, db_index=True, default=None, null=True)),
                ('longitude', models.FloatField(blank=True, db_index=True, default=None, null=True)),
            ],
        ),
    ]
